# NPV Examples

In [1]:
import pandas as pd

## PV Example

In [ ]:
lifetime = 20  # years
discount_rate = 0.08  # per unit
size = 100  # kW
specific_cost = 800  # EUR/kW
fom = 20  # EUR/kW/a fixed operation and maintenance cost
fit = 0.1  # EUR/kWh income per kWh
flh = 1000  # h/a full load hours

flows = pd.DataFrame(index=range(lifetime + 1))
flows["investment"] = [-size * specific_cost] + [0] * lifetime
flows["FOM"] = [0] + [-size * fom] * lifetime
flows["income"] = [0] + [size * flh * fit] * lifetime
flows["total_flow"] = flows.sum(axis=1)
flows["discount_factor"] = [(1 + discount_rate) ** (-t) for t in range(lifetime + 1)]
flows["discounted_total_flow"] = flows["total_flow"] * flows["discount_factor"]

In [3]:
flows.head()

,investment,FOM,income,total_flow,discount_factor,discounted_total_flow
0,-80000,0,0.0,-80000.0,1.000000,-80000.000000
1,0,-2000,10000.0,8000.0,0.925926,7407.407407
2,0,-2000,10000.0,8000.0,0.857339,6858.710562
3,0,-2000,10000.0,8000.0,0.793832,6350.657928
4,0,-2000,10000.0,8000.0,0.735030,5880.238822

In [4]:
flows.sum()

investment               -80000.000000
FOM                      -40000.000000
income                   200000.000000
total_flow                80000.000000
discount_factor              10.818147
discounted_total_flow     -1454.820740
dtype: float64

## Nuclear Example

In [5]:
lifetime = 40  # years
discount_rate = 0.05  # per unit
size = 3e6  # kW
specific_cost = 5000  # EUR/kW
decommissioning_cost = 1000  # EUR/kW
fom = 20  # EUR/kW/a
fuel = 10  # EUR/MWh
market_value = 50  # EUR/MWh
flh = 8000  # h/a

flows = pd.DataFrame(index=range(lifetime + 1))
flows["investment"] = [-size * specific_cost] + [0] * (lifetime - 1) + [-size * decommissioning_cost]
flows["FOM"] = [0] + [-size * fom] * lifetime
flows["income"] = [0] + [size * flh * market_value / 1000] * lifetime
flows["total_flow"] = flows.sum(axis=1)
flows["discount_factor"] = [(1 + discount_rate) ** (-t) for t in range(lifetime + 1)]
flows["discounted_total_flow"] = flows["total_flow"] * flows["discount_factor"]

In [9]:
flows.head()

,investment,FOM,income,total_flow,discount_factor,discounted_total_flow
0,-1.500000e+10,0.0,0.000000e+00,-1.500000e+10,1.000000,-1.500000e+10
1,0.000000e+00,-60000000.0,1.200000e+09,1.140000e+09,0.952381,1.085714e+09
2,0.000000e+00,-60000000.0,1.200000e+09,1.140000e+09,0.907029,1.034014e+09
3,0.000000e+00,-60000000.0,1.200000e+09,1.140000e+09,0.863838,9.847749e+08
4,0.000000e+00,-60000000.0,1.200000e+09,1.140000e+09,0.822702,9.378808e+08

In [7]:
flows.sum()

investment              -1.800000e+10
FOM                     -2.400000e+09
income                   4.800000e+10
total_flow               2.760000e+10
discount_factor          1.815909e+01
discounted_total_flow    4.135221e+09
dtype: float64